# Generated by Django 4.2.1 on 2023-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('otp_timestamp', models.DateTimeField()),
                ('wrong_attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
